"""create appointments table

Revision ID: 000ba258406c
Revises: b7878d08c2d7
Create Date: 2026-08-25 04:57:44.487511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000ba258406c'
down_revision = 'b7878d08c2d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
